#!/usr/bin/env bash
# Build the doc-guard plugin against a local DSH install.
#
# Steps: locate the DSH dependency root → link dev deps → tsc（纯 tsc 构建，
# 产物在 lib/types/，lib/index.js 为转发入口）。Windows 可直接 `npm run
# build:win`（等效 Node 脚本，不需要 bash）。
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# 1. Locate the DSH dependency root and link dev dependencies
CHECKOUT=""
if [ "${1:-}" = "--checkout" ] && [ -n "${2:-}" ]; then
  CHECKOUT="$2"
fi

if [ -n "$CHECKOUT" ]; then
  node scripts/setup-dsh-deps.mjs --checkout "$CHECKOUT"
else
  node scripts/setup-dsh-deps.mjs
fi

BIN="$ROOT/node_modules/.bin"
if [ ! -x "$BIN/tsc" ]; then
  echo "build: 本插件缺少 typescript devDependency，先执行 npm install" >&2
  exit 1
fi

echo "=== Compiling src → lib/types (tsc) ==="
"$BIN/tsc" -p tsconfig.json

echo "=== Ensuring lib/index.js entry ==="
mkdir -p lib
printf "// doc-guard host entry (committed; regenerated by build scripts). tsc output lives in lib/types/.\\nexport * from './types/index.js'\\n" > lib/index.js

echo "=== Build complete ==="
ls -la lib/ lib/types/ | head -20
