#!/usr/bin/env node
/**
 * build-win — Windows 等效构建（不需要 bash/Git Bash）。
 * 步骤与 scripts/build.sh 一致：setup-dsh-deps → tsc → 确保 lib/index.js 入口。
 */
import { spawnSync } from 'node:child_process'
import { mkdir, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const require = createRequire(import.meta.url)

function run(cmd, args) {
  const result = spawnSync(cmd, args, { cwd: ROOT, stdio: 'inherit' })
  if (result.status !== 0) {
    console.error(`build-win: ${cmd} ${args.join(' ')} 失败 (exit ${result.status})`)
    process.exit(result.status ?? 1)
  }
}

// 1. 定位 DSH 依赖根并链接
const argCheckout = process.argv.indexOf('--checkout')
run('node', ['scripts/setup-dsh-deps.mjs', ...(argCheckout >= 0 ? ['--checkout', process.argv[argCheckout + 1]] : [])])

// 2. tsc（直接调 typescript 的 tsc.js，避免 .cmd/shell 问题）
let tscPath
try {
  tscPath = require.resolve('typescript/lib/tsc.js', { paths: [ROOT] })
} catch {
  console.error('build-win: 缺少 typescript devDependency，先执行 npm install')
  process.exit(1)
}
run(process.execPath, [tscPath, '-p', 'tsconfig.json'])

// 3. 确保 lib/index.js 转发入口存在（tsc 不产出该文件）
await mkdir(join(ROOT, 'lib'), { recursive: true })
await writeFile(
  join(ROOT, 'lib', 'index.js'),
  "// doc-guard host entry (committed; regenerated by build scripts). tsc output lives in lib/types/.\nexport * from './types/index.js'\n",
  'utf8',
)
console.log('=== Build complete ===')
